#!/usr/bin/env node
// :diff for the governance-records piece — contract requirement 5.
//
// Reads two local files and writes nothing to Noru:
//   .noru/.cache/governance-records.parsed.json  the validated manifest (validate_manifest.py)
//   .noru/.cache/noru-state.json                 existing evidence and its control links, written
//                                                by the skill from getOrganizationEvidence
//
// No idempotency key is documented for evidence, so this piece does not assume one: every record
// lands with a marker in its description that contains the record key and a digest of the rendered
// account, and the diff looks for that marker in the evidence already in the organization. Same
// key, same content -> skip. Same key, changed content -> a new record, because minutes that have
// been rewritten are a different account and an auditor should see both.
//
// Usage: node diff.mjs [--repo=<path>] [--output=json|text] [--quiet]
// Exit codes: 0 plan written, 1 missing/unusable input, 2 usage error.

import { createHash } from "node:crypto";
import { existsSync, readFileSync, realpathSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import {
  parseCommonArgs,
  planPathFor,
  renderPlanText,
  sha256OfFile,
  summarize,
  writePlan,
} from "./lib/plan.mjs";

const PIECE = "governance-records";
const MARKER_PREFIX = "noru-grc-engineering:governance-records";
const USAGE = "usage: diff.mjs [--repo=<path>] [--output=json|text] [--quiet]\n";

export function recordMarker(key, contentDigest) {
  return `[${MARKER_PREFIX}#${key}@${contentDigest.slice(0, 16)}]`;
}

function digest(text) {
  return createHash("sha256").update(text).digest("hex");
}

function loadJson(path, label) {
  if (!existsSync(path)) return { error: `${label} not found at ${path}` };
  try {
    return { value: JSON.parse(readFileSync(path, "utf8")) };
  } catch (error) {
    return { error: `${label} at ${path} is not readable JSON (${error.message})` };
  }
}

function participantLine(participant) {
  const role = participant.role ? ` (${participant.role})` : "";
  const attendance = participant.attendance ?? "present";
  return `  - ${participant.name}${role} [${attendance}]`;
}

function actionLine(action) {
  const due = action.due_on ? `, due ${action.due_on}` : ", no due date";
  const status = action.status ? ` [${action.status}]` : "";
  return `  - ${action.description} — owner ${action.owner}${due}${status}`;
}

/**
 * The evidence body. This is what an auditor reads, so it says who, when, what was decided, what
 * was assigned to whom, and which file it came from — nothing that is not in the reviewed manifest.
 */
export function recordBody(record, manifest) {
  const src = manifest.source;
  const participants = record.participants ?? [];
  const decisions = record.decisions ?? [];
  const actions = record.actions ?? [];
  const lines = [
    `Governance record: ${record.title}`,
    `Kind: ${record.kind}`,
    `Occurred on: ${record.occurred_on}`,
    `Approved on: ${record.approved_on ?? "(not recorded)"}`,
    `Approved by: ${record.approved_by ?? "(not recorded)"}`,
    `Next review due: ${record.next_review_due ?? "(not set)"}`,
    "",
    `Participants (${participants.length}):`,
    ...(participants.length > 0 ? participants.map(participantLine) : ["  (none recorded)"]),
    "",
    `Decisions (${decisions.length}):`,
    ...(decisions.length > 0 ? decisions.map((d) => `  - ${d}`) : ["  (none recorded)"]),
    "",
    `Actions (${actions.length}):`,
    ...(actions.length > 0 ? actions.map(actionLine) : ["  (none recorded)"]),
    "",
    `Interpretation owner: ${record.interpretation.owner}`,
    `Decided: ${record.interpretation.decided_at}`,
    `Expires: ${record.interpretation.expires_at ?? `(not set; next review due ${record.next_review_due})`}`,
    `Rationale: ${record.interpretation.rationale}`,
    "",
    `Source document: ${record.document.file} (sha256 ${record.document.sha256})`,
    "Read from:",
    ...(record.refs ?? []).map((r) => `  - ${r}`),
    "",
    `Source: ${src.slug} @ ${src.commit_sha} (${src.branch})`,
    `Generated by: ${src.generated_by}`,
  ];
  return lines.join("\n");
}

function mappingArgs(mapping) {
  return {
    controlId: mapping.control_id,
    ...(mapping.evidence_item_ids && mapping.evidence_item_ids.length > 0
      ? { evidenceItemIds: mapping.evidence_item_ids }
      : {}),
  };
}

/**
 * The state snapshot is untrusted tool output. It is compared against, never obeyed.
 */
export function buildOperations(manifest, state) {
  const evidence = state.evidence ?? [];
  const src = manifest.source;
  const operations = [];

  for (const record of manifest.records ?? []) {
    const body = recordBody(record, manifest);
    const marker = recordMarker(record.key, digest(body));
    const title = `${record.title} (${record.occurred_on})`;
    const existing = evidence.find((e) => String(e.description ?? "").includes(marker));
    const superseded = evidence.find(
      (e) =>
        !String(e.description ?? "").includes(marker) &&
        String(e.description ?? "").includes(`${MARKER_PREFIX}#${record.key}@`)
    );

    operations.push({
      operation: "createEvidence",
      transport: "mcp",
      scope: "write:evidence",
      subject: `${record.kind}: ${title}`,
      effect: existing ? "skip" : "create",
      reason: existing
        ? `evidence ${existing.id} already carries this record's exact content marker`
        : superseded
          ? `evidence ${superseded.id} covers record '${record.key}' but the account has changed; ` +
            "a new record will be created so both accounts remain visible (no idempotency key is " +
            "documented for evidence — see the gap note in piece.json)"
          : "no evidence carries this record's marker yet",
      idempotency: { kind: "client_probe", key: ["description contains marker"], marker },
      arguments: {
        title,
        description:
          `${marker} ${record.kind} for ${record.occurred_on}, filed by ${record.interpretation.owner} ` +
          `on ${record.interpretation.decided_at}. Source: ${src.slug} @ ${src.commit_sha} (${src.branch}).`,
        content: body,
        tags: [PIECE, record.kind],
        controlMappings: (record.control_mappings ?? []).map(mappingArgs),
      },
    });

    // Only reachable when the evidence already exists: createEvidence carries the mappings itself,
    // so a link operation is for a mapping added to the manifest after the record was pushed.
    if (!existing) continue;
    const linked = new Set(
      (existing.linkedControls ?? []).map((c) => String(c.id ?? c.controlId ?? "").toLowerCase())
    );
    for (const mapping of record.control_mappings ?? []) {
      if (linked.has(String(mapping.control_id).toLowerCase())) continue;
      operations.push({
        operation: "linkEvidenceToControl",
        transport: "mcp",
        scope: "write:evidence",
        subject: `${record.key} -> ${mapping.control_id}`,
        effect: "create",
        reason:
          `evidence ${existing.id} exists but is not linked to '${mapping.control_id}'; the mapping ` +
          "was added to the manifest after the record was filed",
        idempotency: { kind: "client_probe", key: ["evidenceId", "controlId"] },
        arguments: { evidenceId: existing.id, ...mappingArgs(mapping) },
      });
    }
  }

  return operations;
}

function main(argv) {
  const opts = parseCommonArgs(argv);
  if (opts.help) {
    process.stdout.write(USAGE);
    return 0;
  }
  if (opts.rest.length > 0) {
    process.stderr.write(`error: unexpected argument '${opts.rest[0]}'\n${USAGE}`);
    return 2;
  }

  const manifestPath = join(opts.repo, ".noru", "governance-records.yml");
  const parsedPath = join(opts.repo, ".noru", ".cache", "governance-records.parsed.json");
  const statePath = join(opts.repo, ".noru", ".cache", "noru-state.json");

  if (!existsSync(manifestPath)) {
    process.stderr.write(
      `error: no manifest at ${manifestPath} — run the piece's :scan command first\n`
    );
    return 1;
  }
  const parsed = loadJson(parsedPath, "validated manifest");
  if (parsed.error) {
    process.stderr.write(
      `error: ${parsed.error}\n` +
        "hint: python3 <plugin>/scripts/validate_manifest.py .noru/governance-records.yml " +
        "--emit-parsed=.noru/.cache/governance-records.parsed.json\n"
    );
    return 1;
  }
  const state = loadJson(statePath, "Noru state snapshot");
  if (state.error) {
    process.stderr.write(
      `error: ${state.error}\n` +
        "hint: the skill writes this from getOrganizationEvidence before running :diff\n"
    );
    return 1;
  }

  const manifest = parsed.value;
  const operations = buildOperations(manifest, state.value);
  const plan = writePlan(planPathFor(opts.repo, PIECE), {
    repo: opts.repo,
    state: state.value,
    created_at: state.value.fetched_at ?? manifest.source.commit_sha,
    piece: PIECE,
    manifest: ".noru/governance-records.yml",
    manifest_sha256: sha256OfFile(manifestPath),
    provenance: {
      slug: manifest.source.slug,
      commit_sha: manifest.source.commit_sha,
      branch: manifest.source.branch,
    },
    operations,
    summary: summarize(operations),
  });

  if (opts.json) {
    process.stdout.write(`${JSON.stringify(plan, null, opts.quiet ? 0 : 2)}\n`);
  } else if (!opts.quiet) {
    process.stdout.write(`${renderPlanText(plan)}\n`);
  }
  return 0;
}

// Reduce both sides to one form before comparing: `import.meta.url` is the realpath and is
// percent-encoded, while `process.argv[1]` is the path as it was typed — and /tmp and /var are
// symlinks on macOS, so the two differ routinely. A raw comparison is then false and the script
// exits 0 having done nothing. realpathSync throws when argv[1] is not a path at all (`node -e`,
// or an import), which is not a direct invocation either.
function invokedAsScript() {
  try {
    return import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href;
  } catch {
    return false;
  }
}

if (invokedAsScript()) {
  process.exit(main(process.argv.slice(2)));
}
