#!/usr/bin/env node
// :diff for the iac-scan piece — contract requirement 5.
//
// Reads two local files and writes nothing to Noru:
//   .noru/.cache/iac-scan.parsed.json  the validated manifest (validate_manifest.py)
//   .noru/.cache/noru-state.json       the findings this piece already has in Noru, written by the
//                                      skill from getSecurityFindings filtered on this source
//
// Every operation is the same call, and that is the point of this piece: createSecurityFinding is
// documented as an idempotent upsert on (source, externalId), so landing a finding and closing one
// are the same write with a different status. There is no probe, no marker embedded in a
// description, and no second call to fix up a field the create could not set.
//
// Two halves:
//
//   the manifest    every reviewed finding, upserted on its own key.
//   the queue       every finding Noru still holds for this repository that no rule reproduced.
//                   Those are resolved. A scanner that only ever adds is a scanner whose register
//                   grows for ever, and the closing half is the one a laptop run cannot do without
//                   asking Noru what it already said.
//
// Reconciliation is scoped to this repository: an externalId is `<slug>:<key>`, and only findings
// carrying this repository's slug are ever closed. Two repositories pushing under one source must
// not close each other's work.
//
// Usage: node diff.mjs [--repo=<path>] [--output=json|text] [--quiet]
// Exit codes: 0 plan written, 1 missing/unusable input, 2 usage error.

import { existsSync, readFileSync, realpathSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import {
  parseCommonArgs,
  planPathFor,
  renderPlanText,
  sha256OfFile,
  summarize,
  writePlan,
} from "./lib/plan.mjs";

const PIECE = "iac-scan";
const FINDING_SOURCE = "iac-scan";
const USAGE = "usage: diff.mjs [--repo=<path>] [--output=json|text] [--quiet]\n";

// What makes a re-run a no-op. `raw` is deliberately absent: it carries the commit the write came
// from, so comparing it would make every commit an update and "idempotent" would mean nothing.
// Provenance travels on every write; it is not part of what the write is about.
const COMPARED_FIELDS = [
  "title", "severity", "status", "category", "checkName", "description", "observedAt",
  "assetId", "riskId", "ownerEmail",
];

export function externalIdFor(slug, key) {
  return `${slug}:${key}`;
}

/** The observation as an RFC 3339 instant, which is what the published input schema asks for. */
export function observedInstant(isoDate) {
  return `${isoDate}T00:00:00Z`;
}

function loadJson(path, label) {
  if (!existsSync(path)) return { error: `${label} not found at ${path}` };
  try {
    return { value: JSON.parse(readFileSync(path, "utf8")) };
  } catch (error) {
    return { error: `${label} at ${path} is not readable JSON (${error.message})` };
  }
}

/**
 * The finding body. Everything here is in the reviewed manifest; nothing is the matched line, which
 * this piece never records — one of the rules fires on a line that holds a credential.
 */
export function findingDescription(finding, manifest) {
  const src = manifest.source;
  const lines = [
    finding.title,
    "",
    `Rule: ${finding.check} (${finding.technology})`,
    `Where: ${finding.file}${finding.resource ? ` — ${finding.resource}` : ""}`,
    `Observed on: ${finding.observed_on}`,
    "",
    "Cited at:",
    ...(finding.refs ?? []).map((r) => `  - ${r}`),
    "",
    `Decided by: ${finding.interpretation.owner} on ${finding.interpretation.decided_at}`,
    `Stands until: ${finding.interpretation.expires_at}`,
    `Reasoning: ${finding.interpretation.rationale}`,
    "",
    `Source: ${src.slug} @ ${src.commit_sha} (${src.branch})`,
    `Generated by: ${src.generated_by}`,
  ];
  return lines.join("\n");
}

function provenanceOf(manifest) {
  const src = manifest.source;
  return { slug: src.slug, commit_sha: src.commit_sha, branch: src.branch };
}

function assetIdFor(manifest, externalId) {
  if (!externalId) return null;
  const match = (manifest.queue_snapshot?.assets ?? []).find(
    (asset) => asset.external_id === externalId
  );
  return match ? match.id : null;
}

function changedFields(desired, existing) {
  return COMPARED_FIELDS.filter((field) => {
    const wanted = desired[field] ?? null;
    // A field the piece does not set is a field it does not have an opinion about, so an existing
    // value there is not a difference to reconcile.
    if (wanted === null) return false;
    return (existing[field] ?? null) !== wanted;
  });
}

/**
 * The state snapshot is untrusted tool output. It is compared against, never obeyed.
 */
export function buildOperations(manifest, state) {
  const existingFindings = (state.security_findings ?? []).filter(
    (row) => (row.source ?? FINDING_SOURCE) === FINDING_SOURCE
  );
  const byExternalId = new Map(existingFindings.map((row) => [row.externalId, row]));
  const slug = manifest.source.slug;
  const provenance = provenanceOf(manifest);
  const operations = [];
  const claimed = new Set();

  for (const finding of manifest.findings ?? []) {
    const externalId = externalIdFor(slug, finding.key);
    claimed.add(externalId);
    const desired = {
      source: FINDING_SOURCE,
      externalId,
      title: finding.title,
      severity: finding.severity,
      status: finding.status,
      category: finding.category,
      checkName: finding.check,
      description: findingDescription(finding, manifest),
      observedAt: observedInstant(finding.observed_on),
      assetId: assetIdFor(manifest, finding.asset_external_id),
      riskId: finding.risk_id ?? null,
      ownerEmail: finding.owner_email ?? null,
    };
    const existing = byExternalId.get(externalId);
    const drifted = existing ? changedFields(desired, existing) : [];

    operations.push({
      operation: "createSecurityFinding",
      transport: "mcp",
      scope: "write:risks",
      subject: `${finding.severity}: ${finding.check} in ${finding.file}`,
      effect: existing ? (drifted.length > 0 ? "update" : "skip") : "create",
      reason: existing
        ? drifted.length > 0
          ? `finding ${existing.id ?? externalId} already exists; ${drifted.join(", ")} would change`
          : `finding ${existing.id ?? externalId} already says exactly this`
        : "no finding carries this externalId yet",
      idempotency: {
        kind: "server_upsert",
        key: ["source", "externalId"],
      },
      arguments: {
        ...desired,
        ...(desired.assetId === null ? {} : { assetExternalId: finding.asset_external_id }),
        raw: {
          ...provenance,
          generated_by: manifest.source.generated_by,
          rule: finding.check,
          resource: finding.resource ?? null,
          refs: finding.refs ?? [],
        },
      },
    });
  }

  // The closing half. Only this repository's own findings, and only the ones no rule reproduced.
  const mine = `${slug}:`;
  const orphans = existingFindings
    .filter((row) => String(row.externalId ?? "").startsWith(mine))
    .filter((row) => !claimed.has(row.externalId))
    .sort((a, b) => (a.externalId < b.externalId ? -1 : a.externalId > b.externalId ? 1 : 0));

  for (const row of orphans) {
    const alreadyClosed = row.status === "resolved";
    operations.push({
      operation: "createSecurityFinding",
      transport: "mcp",
      scope: "write:risks",
      subject: `close: ${row.checkName ?? row.externalId}`,
      effect: alreadyClosed ? "skip" : "update",
      reason: alreadyClosed
        ? `${row.externalId} is already resolved in Noru`
        : `${row.externalId} is ${row.status ?? "open"} in Noru and no rule reproduced it at ` +
          `${provenance.commit_sha} — the same keyed upsert closes it`,
      idempotency: {
        kind: "server_upsert",
        key: ["source", "externalId"],
      },
      arguments: {
        source: FINDING_SOURCE,
        externalId: row.externalId,
        title: row.title,
        severity: row.severity,
        status: "resolved",
        category: row.category,
        checkName: row.checkName,
        raw: {
          ...provenance,
          generated_by: manifest.source.generated_by,
          closed_because: "no bundled rule reproduced this finding at this commit",
        },
      },
    });
  }

  return operations;
}

function main(argv) {
  const opts = parseCommonArgs(argv);
  if (opts.help) {
    process.stdout.write(USAGE);
    return 0;
  }
  if (opts.rest.length > 0) {
    process.stderr.write(`error: unexpected argument '${opts.rest[0]}'\n${USAGE}`);
    return 2;
  }

  const manifestPath = join(opts.repo, ".noru", "iac-scan.yml");
  const parsedPath = join(opts.repo, ".noru", ".cache", "iac-scan.parsed.json");
  const statePath = join(opts.repo, ".noru", ".cache", "noru-state.json");

  if (!existsSync(manifestPath)) {
    process.stderr.write(
      `error: no manifest at ${manifestPath} — run the piece's :scan command first\n`
    );
    return 1;
  }
  const parsed = loadJson(parsedPath, "validated manifest");
  if (parsed.error) {
    process.stderr.write(
      `error: ${parsed.error}\n` +
        "hint: python3 <plugin>/scripts/validate_manifest.py .noru/iac-scan.yml " +
        "--emit-parsed=.noru/.cache/iac-scan.parsed.json\n"
    );
    return 1;
  }
  const state = loadJson(statePath, "Noru state snapshot");
  if (state.error) {
    process.stderr.write(
      `error: ${state.error}\n` +
        "hint: the skill writes this from getSecurityFindings before running :diff. Without it the " +
        "plan cannot tell a new finding from one that is already filed, and cannot close anything\n"
    );
    return 1;
  }

  const manifest = parsed.value;
  const operations = buildOperations(manifest, state.value);
  const plan = writePlan(planPathFor(opts.repo, PIECE), {
    repo: opts.repo,
    state: state.value,
    created_at: state.value.fetched_at ?? manifest.source.commit_sha,
    piece: PIECE,
    manifest: ".noru/iac-scan.yml",
    manifest_sha256: sha256OfFile(manifestPath),
    provenance: provenanceOf(manifest),
    operations,
    summary: summarize(operations),
  });

  if (opts.json) {
    process.stdout.write(`${JSON.stringify(plan, null, opts.quiet ? 0 : 2)}\n`);
  } else if (!opts.quiet) {
    process.stdout.write(`${renderPlanText(plan)}\n`);
  }
  return 0;
}

// Reduce both sides to one form before comparing: `import.meta.url` is the realpath and is
// percent-encoded, while `process.argv[1]` is the path as it was typed — and /tmp and /var are
// symlinks on macOS, so the two differ routinely. A raw comparison is then false and the script
// exits 0 having done nothing. realpathSync throws when argv[1] is not a path at all (`node -e`,
// or an import), which is not a direct invocation either.
function invokedAsScript() {
  try {
    return import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href;
  } catch {
    return false;
  }
}

if (invokedAsScript()) {
  process.exit(main(process.argv.slice(2)));
}
