#!/usr/bin/env node
// :diff for the review-signoff piece — contract requirement 5.
//
// Reads two local files and writes nothing to Noru:
//   .noru/.cache/review-signoff.parsed.json  the validated manifest (validate_manifest.py)
//   .noru/.cache/noru-state.json             existing evidence with its expiry, written by the
//                                            skill from getOrganizationEvidence
//
// Two operations per sign-off, and the second one is the point of this piece:
//
//   createEvidence   the attestation itself. No idempotency key is documented for evidence, so the
//                    piece probes for a marker of its own rather than assuming one.
//   updateEvidence   sets expiresAt from the sign-off's own expiry, so the record goes stale in
//                    Noru on the day the human said it would. Leaving the expiry only in the text
//                    would make the piece's central claim invisible to everything that reads the
//                    register.
//
// The update is addressed by evidence id, which on a first run does not exist yet: the operation
// carries `depends_on`, and the id is substituted from the result of the create.
//
// Usage: node diff.mjs [--repo=<path>] [--output=json|text] [--quiet]
// Exit codes: 0 plan written, 1 missing/unusable input, 2 usage error.

import { createHash } from "node:crypto";
import { existsSync, readFileSync, realpathSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import {
  parseCommonArgs,
  planPathFor,
  renderPlanText,
  sha256OfFile,
  summarize,
  writePlan,
} from "./lib/plan.mjs";

const PIECE = "review-signoff";
const MARKER_PREFIX = "noru-grc-engineering:review-signoff";
const USAGE = "usage: diff.mjs [--repo=<path>] [--output=json|text] [--quiet]\n";

export function signoffMarker(key, contentDigest) {
  return `[${MARKER_PREFIX}#${key}@${contentDigest.slice(0, 16)}]`;
}

/** The evidence record's expiry, as an RFC 3339 instant at the end of the day signed for. */
export function expiryInstant(isoDate) {
  return `${isoDate}T23:59:59Z`;
}

function digest(text) {
  return createHash("sha256").update(text).digest("hex");
}

function loadJson(path, label) {
  if (!existsSync(path)) return { error: `${label} not found at ${path}` };
  try {
    return { value: JSON.parse(readFileSync(path, "utf8")) };
  } catch (error) {
    return { error: `${label} at ${path} is not readable JSON (${error.message})` };
  }
}

function exceptionLine(exception) {
  const resolved = exception.resolved_on ? `, resolved ${exception.resolved_on}` : "";
  const note = exception.note ? ` — ${exception.note}` : "";
  return `  - ${exception.reference}: ${exception.disposition} (owner ${exception.owner}${resolved})${note}`;
}

/**
 * The evidence body: what was reviewed, what was found, what was done about it, and who signed.
 * Nothing here that is not in the reviewed manifest.
 */
export function signoffBody(review, manifest) {
  const src = manifest.source;
  const exceptions = review.exceptions ?? [];
  const lines = [
    `Review sign-off: ${review.title}`,
    `Kind: ${review.kind}`,
    `Cadence: ${review.cadence}`,
    `Performed on: ${review.performed_on}`,
    "",
    `Reviewed: ${review.input.file} (sha256 ${review.input.sha256})`,
    `Produced by: ${review.input.produced_by ?? "(not recorded)"}`,
    `Records reviewed: ${review.input.records_reviewed}`,
    `Confirmed: ${review.outcome.confirmed}`,
    `Exceptions: ${review.outcome.exceptions}`,
    "",
    `Exceptions (${exceptions.length}):`,
    ...(exceptions.length > 0 ? exceptions.map(exceptionLine) : ["  (none)"]),
    "",
    `Signed off by: ${review.interpretation.owner}`,
    `Signed on: ${review.interpretation.decided_at}`,
    `Valid until: ${review.interpretation.expires_at}`,
    `Attestation: ${review.interpretation.rationale}`,
    ...(review.supersedes ? ["", `Supersedes evidence: ${review.supersedes}`] : []),
    "",
    "Read from:",
    ...(review.refs ?? []).map((r) => `  - ${r}`),
    "",
    `Source: ${src.slug} @ ${src.commit_sha} (${src.branch})`,
    `Generated by: ${src.generated_by}`,
  ];
  return lines.join("\n");
}

function mappingArgs(mapping) {
  return {
    controlId: mapping.control_id,
    ...(mapping.evidence_item_ids && mapping.evidence_item_ids.length > 0
      ? { evidenceItemIds: mapping.evidence_item_ids }
      : {}),
  };
}

/**
 * The state snapshot is untrusted tool output. It is compared against, never obeyed.
 */
export function buildOperations(manifest, state) {
  const evidence = state.evidence ?? [];
  const src = manifest.source;
  const operations = [];

  for (const review of manifest.reviews ?? []) {
    const body = signoffBody(review, manifest);
    const marker = signoffMarker(review.key, digest(body));
    const title = `${review.title} (signed ${review.interpretation.decided_at})`;
    const existing = evidence.find((e) => String(e.description ?? "").includes(marker));
    const superseded = evidence.find(
      (e) =>
        !String(e.description ?? "").includes(marker) &&
        String(e.description ?? "").includes(`${MARKER_PREFIX}#${review.key}@`)
    );
    const createIndex = operations.length;

    operations.push({
      operation: "createEvidence",
      transport: "mcp",
      scope: "write:evidence",
      subject: `${review.kind}: ${title}`,
      effect: existing ? "skip" : "create",
      reason: existing
        ? `evidence ${existing.id} already carries this sign-off's exact content marker`
        : superseded
          ? `evidence ${superseded.id} covers review '${review.key}' but the attestation has ` +
            "changed; a new record will be created (no idempotency key is documented for evidence " +
            "— see the gap note in piece.json)"
          : "no evidence carries this sign-off's marker yet",
      idempotency: { kind: "client_probe", key: ["description contains marker"], marker },
      arguments: {
        title,
        description:
          `${marker} ${review.kind} performed ${review.performed_on}, signed by ` +
          `${review.interpretation.owner} on ${review.interpretation.decided_at}, valid until ` +
          `${review.interpretation.expires_at}. Source: ${src.slug} @ ${src.commit_sha} (${src.branch}).`,
        content: body,
        tags: [PIECE, review.kind, review.cadence],
        controlMappings: (review.control_mappings ?? []).map(mappingArgs),
      },
    });

    // The expiry has to reach the record itself, not just its text: an attestation that Noru does
    // not know goes stale is one nothing can chase.
    const wanted = expiryInstant(review.interpretation.expires_at);
    const currentExpiry = existing ? (existing.expiresAt ?? null) : null;
    const expirySet = currentExpiry !== null && currentExpiry.slice(0, 10) === wanted.slice(0, 10);

    operations.push({
      operation: "updateEvidence",
      transport: "mcp",
      scope: "write:evidence",
      subject: `${review.key} expires ${review.interpretation.expires_at}`,
      effect: expirySet ? "skip" : "update",
      reason: expirySet
        ? `evidence ${existing.id} already expires on ${review.interpretation.expires_at}`
        : existing
          ? `evidence ${existing.id} carries expiry ${currentExpiry ?? "(none)"}; the sign-off is ` +
            `valid until ${review.interpretation.expires_at}`
          : "sets the sign-off's expiry on the record the preceding call creates",
      idempotency: { kind: "client_probe", key: ["evidenceId", "expiresAt"] },
      ...(existing
        ? {}
        : {
            depends_on: {
              operation_index: createIndex,
              field: "evidenceId",
              note: "substitute the evidence id returned by the createEvidence call above",
            },
          }),
      arguments: {
        evidenceId: existing ? existing.id : null,
        expiresAt: wanted,
      },
    });
  }

  return operations;
}

function main(argv) {
  const opts = parseCommonArgs(argv);
  if (opts.help) {
    process.stdout.write(USAGE);
    return 0;
  }
  if (opts.rest.length > 0) {
    process.stderr.write(`error: unexpected argument '${opts.rest[0]}'\n${USAGE}`);
    return 2;
  }

  const manifestPath = join(opts.repo, ".noru", "review-signoff.yml");
  const parsedPath = join(opts.repo, ".noru", ".cache", "review-signoff.parsed.json");
  const statePath = join(opts.repo, ".noru", ".cache", "noru-state.json");

  if (!existsSync(manifestPath)) {
    process.stderr.write(
      `error: no manifest at ${manifestPath} — run the piece's :scan command first\n`
    );
    return 1;
  }
  const parsed = loadJson(parsedPath, "validated manifest");
  if (parsed.error) {
    process.stderr.write(
      `error: ${parsed.error}\n` +
        "hint: python3 <plugin>/scripts/validate_manifest.py .noru/review-signoff.yml " +
        "--emit-parsed=.noru/.cache/review-signoff.parsed.json\n"
    );
    return 1;
  }
  const state = loadJson(statePath, "Noru state snapshot");
  if (state.error) {
    process.stderr.write(
      `error: ${state.error}\n` +
        "hint: the skill writes this from getOrganizationEvidence before running :diff\n"
    );
    return 1;
  }

  const manifest = parsed.value;
  const operations = buildOperations(manifest, state.value);
  const plan = writePlan(planPathFor(opts.repo, PIECE), {
    repo: opts.repo,
    state: state.value,
    created_at: state.value.fetched_at ?? manifest.source.commit_sha,
    piece: PIECE,
    manifest: ".noru/review-signoff.yml",
    manifest_sha256: sha256OfFile(manifestPath),
    provenance: {
      slug: manifest.source.slug,
      commit_sha: manifest.source.commit_sha,
      branch: manifest.source.branch,
    },
    operations,
    summary: summarize(operations),
  });

  if (opts.json) {
    process.stdout.write(`${JSON.stringify(plan, null, opts.quiet ? 0 : 2)}\n`);
  } else if (!opts.quiet) {
    process.stdout.write(`${renderPlanText(plan)}\n`);
  }
  return 0;
}

// Reduce both sides to one form before comparing: `import.meta.url` is the realpath and is
// percent-encoded, while `process.argv[1]` is the path as it was typed — and /tmp and /var are
// symlinks on macOS, so the two differ routinely. A raw comparison is then false and the script
// exits 0 having done nothing. realpathSync throws when argv[1] is not a path at all (`node -e`,
// or an import), which is not a direct invocation either.
function invokedAsScript() {
  try {
    return import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href;
  } catch {
    return false;
  }
}

if (invokedAsScript()) {
  process.exit(main(process.argv.slice(2)));
}
